name:                santa
version:             0.1.0.0
github:              jamesdabbs/santa
license:             BSD3
author:              James Dabbs
maintainer:          james.dabbs@gmail.com
copyright:           2020 James Dabbs

extra-source-files:
- README.md

synopsis:            An Advent driver
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jamesdabbs/santa#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- containers
- criterion
- either
- filepath
- lens
- mtl
- optparse-applicative
- protolude
- text

default-extensions:
- DeriveGeneric
- GeneralizedNewtypeDeriving
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: src

executables:
  santa-discover:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - santa
    - directory

tests:
  santa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - santa
    - hspec
