name: hs
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '12 13 * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: quay.io/jamesdabbs/advent-of-code-2020
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache stack dependencies
        uses: actions/cache@v2
        with:
          path: |
            /stack
            hs/.stack-work
            hs/dist-newstyle
          key: v1-${{ runner.os }}-${{ hashFiles('hs/stack.yaml') }}-${{ hashFiles('hs/package.yaml') }}
      - name: Setup
        run: stack setup --no-terminal
        working-directory: ./hs
      - name: Install
        run: stack install --no-terminal --jobs 4
        working-directory: ./hs
      - name: Extract binary and input
        run: |
          mkdir -p /tmp/bin
          cp ~/.local/bin/aoc /tmp/bin/aoc
          cp -r ./inputs /tmp
      - name: Persist binary
        uses: actions/upload-artifact@v2
        with:
          name: aoc
          path: |
            /tmp/bin
            /tmp/inputs

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: quay.io/jamesdabbs/advent-of-code-2020
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache stack dependencies
        uses: actions/cache@v2
        with:
          path: |
            /stack
            hs/.stack-work
            hs/dist-newstyle
          key: v1-${{ runner.os }}-${{ hashFiles('hs/stack.yaml') }}-${{ hashFiles('hs/package.yaml') }}
      - name: Setup
        run: stack setup --no-terminal
        working-directory: ./hs
      - name: Install
        run: stack install --no-terminal --jobs 4
        working-directory: ./hs

      # Lint
      - name: Lint
        run: stack exec hlint .
        working-directory: ./hs

      # Run tests
      - name: Run tests
        run: stack test --coverage --no-terminal
        working-directory: ./hs

      # Report coverage
      - name: Generate lcov report
        run: stack exec hpc-lcov
        working-directory: ./hs
      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./hs/lcov.info
      - name: Extract coverage reports
        run: |
          mkdir /tmp/coverage
          cd ./hs
          cp -r $(stack --no-terminal path --local-hpc-root) /tmp/coverage
          cp lcov.info /tmp/coverage
      - name: Persist coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: /tmp/coverage

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: aoc
          path: /tmp
      - name: Run benchmarks
        run: |
          chmod +x ./bin/aoc
          cd ./bin
          mkdir bench
          ./aoc bench
        working-directory: /tmp
      - uses: actions/upload-artifact@v2
        with:
          name: benchmarks
          path: /tmp/bin/bench
